name: CMake Build PGE Treemap

on:
  push:
    branches: [ "main" ]
    paths:
      - 'source0/**'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libpng-dev

    - name: Get PGE3 header
      run: |
        wget -P source0/src https://raw.githubusercontent.com/OneLoneCoder/olcPixelGameEngine3/refs/heads/main/olcPixelGameEngine3.h
        sudo mkdir -p /home/kiel/src/olcPixelGameEngine3
        sudo ln -s "$GITHUB_WORKSPACE/source0/src/olcPixelGameEngine3.h" /home/kiel/src/olcPixelGameEngine3/olcPixelGameEngine3.h

    - name: Configure CMake
      run: cmake -S source0 -B build -G Ninja -DENABLE_ASAN:BOOL=OFF -DENABLE_LSAN:BOOL=OFF -DENABLE_UBSAN:BOOL=OFF -DCMAKE_BUILD_TYPE=Release

    - name: Build with Ninja
      run: ninja -C build

    - name: Upload build artifact (CI run)
      uses: actions/upload-artifact@v4
      with:
        name: pge_treemap
        path: build/pge_treemap

    - name: Upload binary to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: build/pge_treemap

